# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Lily58 build with mouse emulation'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["lily58_left", "lily58_right"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y\nCONFIG_ZMK_USB_BOOT=y"]'
